version: "3.7"
services:
  ldap:
    build:
      context: ldap
      dockerfile: Dockerfile
      network: host
    ports:
      - 10389:10389
      - 10636:10636
  database:
    build:
      context: postgres
      dockerfile: Dockerfile
      network: host
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  app:
    build:
      context: app
      dockerfile: Dockerfile
      network: host
    container_name: app
    depends_on:
      - database
      - ldap
    links:
      - database
    ports:
      - 2005:2005