version: "3"
services:
  mail:
    build:
      context: mail
      dockerfile: Dockerfile
    ports:
    - 8025:8025
    - 1025:1025
  message-broker:
    build:
      context: message-broker
      dockerfile: Dockerfile
    image: message-broker
    ports:
      - 1414:1414
  ldap:
    build:
      context: ldap
      dockerfile: Dockerfile
    ports:
      - 10389:10389
      - 10636:10636
  database:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432